# Generated by Django 5.2 on 2025-06-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_scinet', '0004_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
