# Generated by Django 5.2 on 2025-05-24 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_scinet", "0009_friendshipmodel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("public", "Publiczny"),
                    ("private", "Prywatny"),
                    ("friends", "Tylko dla znajomych"),
                ],
                default="public",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ArticleWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_scinet.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Watch",
                "verbose_name_plural": "Article Watches",
                "unique_together": {("user", "article")},
            },
        ),
    ]
